name: devops_project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.18
  - numpy=1.24.4
  - seaborn=0.12.2
  - matplotlib=3.8.0
  - notebook=7.0.6
  - jupyterlab=4.0.7
  - jupyter_core=5.5.0
  - numba=0.57.1
  - pandas=2.0.3
  - pip=23.2.1
  - joblib=1.3.2
  - imbalanced-learn=0.11.0
  - scikit-learn=1.3.2
  - openpyxl=3.1.2
  - jupytext=1.15.1
  - cookiecutter 1.7.3
  - pytest=7.4.0
  - pytest-mock=3.12.0
  - pyyaml=6.0.1
  - hydra-core=1.3.2
  - requests=2.31.0
  - pip:
      - ydata_profiling==4.6.1
      - lime==0.2.0.1
      - shap==0.43.0
      - witwidget==1.8.1
      - wandb==0.15.12
      - mlflow[extras]==2.8.0
