name: model_interpretability
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.*
  - pandas=2.0.*
  - matplotlib=3.7.*
  - numpy=1.24.*
  - pip=23.3.*
  - scikit-learn=1.3.*
  - pip:
      - wandb==0.16.*
      - mlflow[extras]==2.9.*
      - shap==0.43.*
      - lime==0.2.0.*