name: prep_conda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.6
  - pandas=2.0.3
  - pip=23.2.1
  - request=2.83.1
  - openpyxl=3.1.2
  - scikit-learn=1.3.2
  - pip:
      - wandb==0.15.12